package org.mrshoffen.tasktracker.commons.web.permissions;

public enum Permission {
    DELETE_WORKSPACE,
    UPDATE_WORKSPACE,

    ASSIGN_PERMISSIONS_TO_USER,

    READ_WORKSPACE_CONTENT,
    CREATE_WORKSPACE_CONTENT,
    UPDATE_WORKSPACE_CONTENT,
    DELETE_WORKSPACE_CONTENT,

    WRITE_COMMENTS,
    DELETE_COMMENTS
}
